#Configuration - 配置文件#
Plugin:
#AutoUpdate the plugin when a update is found - 自动更新#
  AutoUpdate: false
  #Debug Mode - 调试模式#
  Debug: false
#Reasons not to add special equipmemt - 不添加附魔的情况#
#If true blocks usage - true是禁止#
Reason:
  Spawner: true
  Egg: true
DropFix:
  #Adds Damages to all drops - 添加伤害#
  Damage: true
#When adding enchantments, only allow safe or item specific enchantments#
SafeEnchant:
  Enabled: false
#Allow the generation of ruins in the map#
Ruins:
  Enabled: true
  Chance: 1
#Allow the drop of custom items (custom.yml)#
Custom:
  Only: false
  Enabled: true
  Chance: 1
#Allow the drop of lore items (lore.txt enhancements)#
Lore:
  Enabled: true
  Chance: 5
  EnhanceAmount: 1
#Changing the way that a few things are displayed#
Display:
  TierName: true
  ColorBlind: false
  ItemMaterialExtras: false
  ItemNameFormat: '%randprefix% %randsuffix%'
#Allow the drop of book to "identify" Magic color items#
IdentifyTome:
  Enabled: true
  Chance: 2
SockettedItem:
  Enabled: true
  Chance: 20
  MinimumSockets: 1
  MaximumSockets: 5
#Allow the drop of socket items#
SocketItem:
  Enabled: true
  Chance: 5
  #Whether to set lore on sockets#
  Lore: true
  Items: 
  - Emerald
  - Diamond
  - Skull_Item
  Colors:
  - GREEN
  - RED
  - BLUE
#This is the initial chance to retrieve an item#
Percentages:
  ChancePerSpawn: 3
#If enabled only worlds listed will be affected#
Worlds:
  Enabled: false
  Allowed:
  - 'world'
  - 'world_nether'
  - 'world_the_end'
