name: DiabloDrops
main: com.modcrafting.diablodrops.DiabloDrops
version: 2.4.504
website: http://dev.bukkit.org/server-mods/diablodrops/
authors: [Deathmarine,Nunnery]
description: >
             物品装备掉落附魔插件
loadbefore: [DiabloBosses, Identify, DiabloLoot, DiabloDungeonBridge]
load: STARTUP

commands:
    diablodrops:
        description: 允许用户生成一种物品
        aliases: [dd, ddrops, diablod]
        usage: /<command> [type]
        permission: diablodrops.dd
permissions:
    diablodrops.dd:
        description: 允许用户生成一种物品
        default: op
    diablodrops.debug:    
        description: 允许用户接受调试信息    
        default: false
    diablodrops.reload:
        description: 允许用户重新加载插件
        default: op
